name: Trivy Security Scan

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t backend:scan ./backend

      - name: Build frontend image
        run: docker build -t frontend:scan ./frontend

      - name: Trivy scan (backend)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: backend:scan
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Trivy scan (frontend)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: frontend:scan
          severity: CRITICAL,HIGH
          exit-code: 1
